version: '3.8'

services:
  dk-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ct-sqlserver
    environment:
      SA_PASSWORD: "SqlServer2019"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    restart: on-failure:5
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P SqlServer2019 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 3

  dk-webapplication1:
    build:
      context: .
      dockerfile: Dockerfile
    image: im-webapplication1
    container_name: ct-webapplication1
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=dk-sqlserver,1433;Database=master;User=sa;Password=SqlServer2019;TrustServerCertificate=True;
      EnableOTLPExporter: true
      Hosts__Jaeger: jaeger-agent
      Hosts__OTLP: otel-collector
    ports:
      - "5001:8080"
    depends_on:
      dk-sqlserver:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.117.0
    container_name: otel-collector
    user: 0:0
    depends_on:
      - jaeger
      - prometheus
      - dk-webapplication1
    volumes:
      - ./config/open-telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - OTELCOL_LOG_LEVEL=debug
    ports:
      - 13133:13133 # health_check extension

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--web.enable-remote-write-receiver' # enable remote write integration
      - '--config.file=/etc/prometheus/prometheus.yml' # default configuration
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    container_name: jaeger
    hostname: jaeger
    ports:
      - 16686:16686

  jaeger-agent:
    container_name: jaeger-agent
    hostname: jaeger-agent
    image: jaegertracing/jaeger-agent:1.62.0
    command: ['--reporter.grpc.host-port=otel-collector:14250']

volumes:
  sqlserverdata:
