# Usage:
# docker compose --profile otel-all up -d
# docker compose --profile otel-grafana up -d

services:
  # Tempo runs as user 10001, and docker compose creates the volume as root. As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:2.6.1
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    profiles:
      - otel-all
      - otel-grafana

  tempo:
    # https://github.com/grafana/tempo/releases
    image: *tempoImage
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../config/tempo.yml:/etc/tempo.yaml
      - tempo:/tmp/tempo
    restart: unless-stopped
    ports:
      - 3200:3200  # tempo
      - 4007:4317  # otlp grpc
    depends_on:
      - otel-collector
    networks:
      - opentelemetry
    profiles:
      - otel-all
      - otel-grafana

  loki:
    # https://github.com/grafana/loki/releases
    image: grafana/loki:3.2.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../config/loki.yml:/etc/loki/local-config.yaml
      - loki:/data/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    networks:
      - opentelemetry
    profiles:
      - otel-all
      - otel-grafana

  grafana:
    # https://github.com/grafana/grafana/releases
    image: grafana/grafana:11.3.0
    container_name: grafana
    #command:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ../config/grafana/provisioning:/etc/grafana/provisioning #https://grafana.com/docs/grafana/latest/administration/provisioning/
    restart: unless-stopped
    ports:
      - 3001:3000
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - opentelemetry
    profiles:
      - otel-all
      - otel-grafana

networks:
  opentelemetry:
    external: true

volumes:
  loki:
  tempo:
  grafana-data:

