# Usage:
# docker compose --profile otel-all up -d
# docker compose --profile otel-prometheus up -d
# docker compose --profile otel-grafana up -d
# docker compose --profile otel-jaeger up -d

services:
  otel-collector:
    container_name: otel-collector
    hostname: otel-collector
    image: otel/opentelemetry-collector-contrib:0.113.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../config/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped
    environment:
      - OTELCOL_LOG_LEVEL=debug
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
      - "9200:55679"  # zpages
      - "13133:13133" # health_check extension
    #   - "14250:14250" # jaeger receiver
    networks:
      - opentelemetry
    profiles:
      - otel-all
      - otel-prometheus
      - otel-grafana
      - otel-jaeger

networks:
  opentelemetry:
    external: true
