global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://dk-webapplication1:8080/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets:
        - otel-collector:8889
        - otel-collector:8888

  - job_name: 'dk-sqlserver'
    scrape_interval: 10s
    static_configs:
      - targets:
        - dk-sqlserver:1433
  - job_name: 'dk-webapplication1'
    scrape_interval: 5s
    static_configs:
      - targets:
        - dk-webapplication1:8080
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090
